[package]
name = "libnest"
version = "0.1.0"
authors = ["Benjamin Grange <benjamin.grange@epitech.eu>",
        "Matteo Melis <matteo.melis@epitech.eu>"]
description = "Backend library to write a package manager for the Raven Operating System."
homepage = "https://raven-os.org"
repository = "https://github.com/raven-os/nest"
keywords = ["package-manager", "package", "manager", "raven", "nest"]
categories = ["command-line-utilities", "development-tools", "filesystem", "os"]

[badges]
travis-ci = { repository = "raven-os/nest" }
maintenance = { status = "actively-developed" }

[dependencies]
toml = "0.4"
curl = "0.4.11"
serde = "1.0.32"
serde_json = "1.0.11"
serde_derive = "1.0.33"
